var nameList = [
  "Time",
  "Past",
  "Future",
  "Dev",
  "Fly",
  "Flying",
  "Soar",
  "Soaring",
  "Power",
  "Falling",
  "Fall",
  "Jump",
  "Cliff",
  "Mountain",
  "Rend",
  "Red",
  "Blue",
  "Green",
  "Yellow",
  "Gold",
  "Demon",
  "Demonic",
  "Panda",
  "Cat",
  "Kitty",
  "Kitten",
  "Zero",
  "Memory",
  "Trooper",
  "XX",
  "Bandit",
  "Fear",
  "Light",
  "Glow",
  "Tread",
  "Deep",
  "Deeper",
  "Deepest",
  "Mine",
  "Your",
  "Worst",
  "Enemy",
  "Hostile",
  "Force",
  "Video",
  "Game",
  "Donkey",
  "Mule",
  "Colt",
  "Cult",
  "Cultist",
  "Magnum",
  "Gun",
  "Assault",
  "Recon",
  "Trap",
  "Trapper",
  "Redeem",
  "Code",
  "Script",
  "Writer",
  "Near",
  "Close",
  "Open",
  "Cube",
  "Circle",
  "Geo",
  "Genome",
  "Germ",
  "Spaz",
  "Shot",
  "Echo",
  "Beta",
  "Alpha",
  "Gamma",
  "Omega",
  "Seal",
  "Squid",
  "Money",
  "Cash",
  "Lord",
  "King",
  "Duke",
  "Rest",
  "Fire",
  "Flame",
  "Morrow",
  "Break",
  "Breaker",
  "Numb",
  "Ice",
  "Cold",
  "Rotten",
  "Sick",
  "Sickly",
  "Janitor",
  "Camel",
  "Rooster",
  "Sand",
  "Desert",
  "Dessert",
  "Hurdle",
  "Racer",
  "Eraser",
  "Erase",
  "Big",
  "Small",
  "Short",
  "Tall",
  "Sith",
  "Bounty",
  "Hunter",
  "Cracked",
  "Broken",
  "Sad",
  "Happy",
  "Joy",
  "Joyful",
  "Crimson",
  "Destiny",
  "Deceit",
  "Lies",
  "Lie",
  "Honest",
  "Destined",
  "Bloxxer",
  "Hawk",
  "Eagle",
  "Hawker",
  "Walker",
  "Zombie",
  "Sarge",
  "Capt",
  "Captain",
  "Punch",
  "One",
  "Two",
  "Uno",
  "Slice",
  "Slash",
  "Melt",
  "Melted",
  "Melting",
  "Fell",
  "Wolf",
  "Hound",
  "Legacy",
  "Sharp",
  "Dead",
  "Mew",
  "Chuckle",
  "Bubba",
  "Bubble",
  "Sandwich",
  "Smasher",
  "Extreme",
  "Multi",
  "Universe",
  "Ultimate",
  "Death",
  "Ready",
  "Monkey",
  "Elevator",
  "Wrench",
  "Grease",
  "Head",
  "Theme",
  "Grand",
  "Cool",
  "Kid",
  "Boy",
  "Girl",
  "Vortex",
  "Paradox",
];

var finalName = "";

export function RandomNameGenerator() {
  return nameList[Math.floor(Math.random() * nameList.length)];
}

export function getRandomComment() {
  const comments = [
    "Great job! 👏👍",
    "I love this! ❤️😍",
    "This is amazing! 🌟✨",
    "Keep up the good work! 💪👊",
    "Awesome! 😎🚀",
    "Fantastic! 🎉🙌",
    "You're a genius! 🤩🧠",
    "Impressive! 👌😲",
    "Outstanding! 🏆👏",
    "I'm speechless! 😶💬",
    "Bravo! 👏👏",
    "Incredible! 😱🤯",
    "You're a rockstar! 🎸🌟",
    "I'm blown away! 💨💥",
    "You're on fire! 🔥🔥",
    "Not bad. 👍😐",
    "It's okay. 🤷‍♂️😐",
    "Meh. 😕👎",
    "Could be better. 🤔👎",
    "Needs improvement. 🛠️👎",
    "Not my cup of tea. 🍵🙅‍♂️",
    "Disappointing. 😞👎",
    "Could have been worse. 🙁👎",
    "Not impressed. 😒👎",
    "Too generic. 🔄👎",
    "Not worth it. 💸👎",
    "Not recommended. ⛔🙅‍♂️",
    "Boring. 😴💤",
    "Lame. 🙄👎",
    "Terrible! 😠👎",
    "Awful! 😨👎",
    "Horrible! 😱👎",
    "Waste of time. ⏳👎",
    "I hate this. 😡👎",
    "I can't stand it. 😤👎",
    "Really disappointing. 😞👎",
    "Just awful. 😫👎",
    "I regret watching this. 😭👎",
    "I'm not impressed at all. 😒👎",
    "I'm not a fan. 🙅‍♂️👎",
    "This is a letdown. 😔👎",
    "I wouldn't recommend it. ⛔🙅‍♂️",
    "Not worth the hype. 🎈👎",
    "Very overrated. ⭐👎",
    "I expected better. 🤷‍♂️👎",
    "I'm underwhelmed. 😐👎",
    "I wouldn't watch it again. 🙅‍♂️👎",
    "Total disappointment. 😞👎",
    "I'm not happy with this. 😕👎",
  ];

  const randomIndex = Math.floor(Math.random() * comments.length);
  return comments[randomIndex];
}
